[project]
name = "pypoli"
version = "0.1.0"
description = "A JAX-based Pauli Propagation Library"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jax>=0.8.2",
]

[dependency-groups]
dev = [
    "flax>=0.12.0",
    "ipykernel",
    "matplotlib>=3.10.8",
    "mcp>=1.25.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv.workspace]
members = [
    "tools/mcp-tools",
]
